/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchQueryRouteImport } from './routes/search/$query'
import { Route as MealsMealIdRouteImport } from './routes/meals/$mealId'
import { Route as CategoryCategoryNameRouteImport } from './routes/category/$categoryName'
import { Route as AreaAreaNameRouteImport } from './routes/area/$areaName'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchQueryRoute = SearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsMealIdRoute = MealsMealIdRouteImport.update({
  id: '/meals/$mealId',
  path: '/meals/$mealId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryNameRoute = CategoryCategoryNameRouteImport.update({
  id: '/category/$categoryName',
  path: '/category/$categoryName',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAreaNameRoute = AreaAreaNameRouteImport.update({
  id: '/area/$areaName',
  path: '/area/$areaName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/area/$areaName': typeof AreaAreaNameRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/search/$query': typeof SearchQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/area/$areaName': typeof AreaAreaNameRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/search/$query': typeof SearchQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/area/$areaName': typeof AreaAreaNameRoute
  '/category/$categoryName': typeof CategoryCategoryNameRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/search/$query': typeof SearchQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/area/$areaName'
    | '/category/$categoryName'
    | '/meals/$mealId'
    | '/search/$query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/area/$areaName'
    | '/category/$categoryName'
    | '/meals/$mealId'
    | '/search/$query'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/area/$areaName'
    | '/category/$categoryName'
    | '/meals/$mealId'
    | '/search/$query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreaAreaNameRoute: typeof AreaAreaNameRoute
  CategoryCategoryNameRoute: typeof CategoryCategoryNameRoute
  MealsMealIdRoute: typeof MealsMealIdRoute
  SearchQueryRoute: typeof SearchQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$mealId': {
      id: '/meals/$mealId'
      path: '/meals/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof MealsMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryName': {
      id: '/category/$categoryName'
      path: '/category/$categoryName'
      fullPath: '/category/$categoryName'
      preLoaderRoute: typeof CategoryCategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/$areaName': {
      id: '/area/$areaName'
      path: '/area/$areaName'
      fullPath: '/area/$areaName'
      preLoaderRoute: typeof AreaAreaNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreaAreaNameRoute: AreaAreaNameRoute,
  CategoryCategoryNameRoute: CategoryCategoryNameRoute,
  MealsMealIdRoute: MealsMealIdRoute,
  SearchQueryRoute: SearchQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
